### ISSUE TITLE
React18 + VITE 在配置 antd时，  Select组件下拉菜单栏不显示

### ISSUE THREAD

**Issue by zdJOJO** [beichensky/Blog#17]
React18 + VITE 在配置 antd时，  Select组件下拉菜单栏不显示

![image](https://user-images.githubusercontent.com/25069798/173287616-e6249aac-bb60-4a97-ab3d-a1140d3bf894.png)

**Comment by beichensky** [comment]
你好，我在本地使用 React18 + Vite 搭建了 React 的开发环境。
并且使用了 antd 官网中 Select 组件提供的前两个例子中的代码。

在浏览器的展示效果中，没有出现 **Select组件下拉菜单栏不显示** 的问题。
目前这个问题是否还存在呢？如果存在的话能否提供一下复现的步骤或者可演示的 Demo 地址。

此外，如果遇到技术相关的问题，欢迎在本仓库对应的文章下进行留言。
倘若没有对应的文章，在任意文章下留言即可。
